[project]
name = "gb-training-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "albumentations>=2.0.8",
    "catboost>=1.2.10",
    "httpx>=0.28.1",
    "huggingface-hub>=1.18.0",
    "ipywidgets>=8.1.8",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "optuna>=4.6.0",
    "pandas>=2.3.1",
    "pillow>=12.2.0",
    "pydantic>=2.13.4",
    "pyarrow>=24.0.0",
    "pyprojroot>=0.3.0",
    "pytorch-lightning>=2.6.5",
    "scikit-learn>=1.9.0",
    "tensorboard>=2.20.0",
    "timm>=1.0.27",
    "torch>=2.12.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.27.0",
    "transformers>=5.11.0",
    "uuid6>=2025.0.1",
]
